# Generated by Django 5.1.2 on 2024-10-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todomodel_time_stamp_todomodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todomodel',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='todomodel',
            name='status',
        ),
    ]
